services:
  - type: web
    name: eduadmin-backend
    env: node
    rootDir: server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
